Repository Kirbitz/CS458-SchedulingTool, pull requests merged in 2022-10, with the labels that each got.

#5 Updated dependency Packages
  package-lock.json
  package.json
Labels: Config

#6 ST-9 It tests ship it
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  public/index.html
  server/index.js
  server/server.js
  tests/index.test.js
Labels: Config

#7 ST-9 Testing CodeCov
  .github/workflows/BuildCodeCoverage.yml
  .github/workflows/CodeQLAnalysis.yml
  .gitignore
  codecov.yml
  package-lock.json
  package.json
  public/index.html
  server/server.js
  tests/index.test.js
Labels: Config

#8 ST-9 hopefully that's all of them
  package-lock.json
  package.json
Labels: Config

#25 St 93 - User Login Server Endpoint Document
  documentation/user_login.md
Labels: documentation

#29 St 23 feature/department page
  client/Components/DepAddRemoveFields.jsx
  client/Components/NavigationBar.jsx
  client/Components/PageRoutes.jsx
  client/Components/SaveAndNotify.jsx
  client/EntryPoint.jsx
  client/Pages/.gitkeep
  client/Pages/DepartmentPage.jsx
  client/dataHelper.js
  package-lock.json
  package.json
  server/index.js
  server/login.js
  server/rateLimiters.js
  tests/client_tests/DepAddRemoveFields.test.js
  tests/client_tests/DepartmentPage.test.js
  tests/client_tests/PageRoutes.test.js
  tests/client_tests/SaveAndNotify.test.js
  tests/server_tests/index.test.js
  tests/server_tests/login.test.js
Labels: enhancement
